### ISSUE TITLE
Can't import opml file

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.gpodder.gpodder#1]
I tried importing a file from ~ and ~/gPodder, neither of which worked.

**Comment by ndarilek** [comment]
I thought that portals were automatic and would handle this?

I'm probably going to add `--filesystem=home` soon. Looks like lots of
features don't work, possibly because upstream doesn't use XDG
directories. Maybe that'll fix this.

**Comment by Alexander-Wilms** [comment]
> I thought that portals were automatic and would handle this?

Yes, https://github.com/flathub/io.github.cloose.CuteMarkEd doesn't have --filesystem access, and I can still open files.

**Comment by ndarilek** [comment]
Not sure, then. Sorry, I've been in over my head with this since day 1.
:/ Help welcome.

**Comment by TingPing** [comment]
>  possibly because upstream doesn't use XDG directories

That needs to be fixed before you grant home access. Otherwise it starts saving junk outside of where it should.

**Comment by ndarilek** [comment]
Ugh. I'll grant that it would be nice for upstream to adopt XDG
conventions, but I just wanted to get this packaged, and I don't have
time to maintain upstream patches. Files are placed in nonstandard
locations regardless of whether or not flatpaks are used, so while it
seems like a nice-to-have, ultimately my goal was just getting this
thing working on Atomic Workstation so I didn't need to layer it on the
system level.

**Comment by TingPing** [comment]
@ndarilek It sounds like we need to be more strict about packages that get added here. This shouldn't be a dumping ground for quick-fixes, the packages here should be well maintained and improved with upstreams.

**Comment by ndarilek** [comment]
Sounds wise, though to be fair, I've spent a fair number of hours trying
to get this up to Flathub standards and don't consider that to have been
a "quick fix." These issues would exist regardless of what mechanism is
used to install the package, and upstream seems to be maintaining it,
albeit with a different set of priorities than we might like.

If the intent for Flathub packages is that we're expected to fix
upstream issues, then I think that's a significant enough expectation
that it should be communicated up front. I won't contribute any more
packages unless I'm willing to take that on, and apologize for my
misunderstanding in this instance.

**Comment by TingPing** [comment]
> These issues would exist regardless of what mechanism is
used to install the package, and upstream seems to be maintaining it,
albeit with a different set of priorities than we might like.

I don't think we know that? I see no issue about supporting XDG: https://github.com/gpodder/gpodder/issues?q=is%3Aissue+xdg+is%3Aopen

> If the intent for Flathub packages is that we're expected to fix
upstream issues

The intent is that packages here follow some basic standards, like freedesktop/xdg, and that this work gets submitted upstream.

> Sounds wise, though to be fair, I've spent a fair number of hours trying
to get this up to Flathub standards and don't consider that to have been
a "quick fix."

It isn't my intent to dismiss your work, it is just that in the long term we want the best possible packages.
