### ISSUE TITLE
add optional dependencies

### ISSUE THREAD

**Issue by elelay** [flathub/org.gpodder.gpodder#17]
Thanks for providing the flatpak :+1: 

Would it be possible to add 2 optional but nice to have python dependencies, that I now ship with the Windows and macOS builds:
- [mutagen](https://pypi.org/project/mutagen/) for tagging
- [youtube-dl](https://pypi.org/project/youtube_dl/) for enhanced Youtube compat (download audio only, etc).

Users don't seem to be able to install them [on their own](https://github.com/gpodder/gpodder/issues/808)

**Comment by tpikonen** [comment]
This is fixed in the last two versions.
