### ISSUE TITLE
Cannot search gpodder.net

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.gpodder.gpodder#2]
```
1522290927.088550 [gpodder.gtkui.desktop.podcastdirectory] WARNING: Got exception while loading podcasts: the JSON object must be str, not 'bytes'
```

The soundcloud search works, however.

**Comment by Alexander-Wilms** [comment]
Oh, right. I've reported the directory.opml 404 upstream. I'll check if the search is broken as well when running gPodder from git.

**Comment by Alexander-Wilms** [comment]
I've found comments stating that this is related to Python 3.5. Since I habe 3.6 in the host, this would explain the discrepancy.

**Comment by nedrichards** [comment]
OK - so this will need an upgrade to the GNOME 3.30 runtime which uses the FDo 18.08 SDK.

**Comment by tpikonen** [comment]
The search in 'Find new podcasts' dialog works for me in gPodder 3.10.21 from flathub. If it does not work for you, please reopen.
